import type { Metadata } from "next";
import {Poppins} from "next/font/google";
import {Merriweather} from "next/font/google";
import {Open_Sans} from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import Header from "./components/Header";

const poppins = Poppins({
  subsets: ['latin'],
  weight:'400',
  variable: '--font-poppins'
}) 
const merriweather = Merriweather({
  subsets: ['latin'],
  weight:'700',
  variable: '--font-merriweather'
}) 
const opensans = Open_Sans({
  subsets: ['latin'],
  weight:'500',
  variable: '--font-opensans'
}) 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${merriweather.variable} ${opensans.variable}  antialiased`}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
